version: '3'
services:
  keycloak:
    image: jboss/keycloak
    networks:
      - transaction-network
    ports:
      - 18443:8443
      - 18080:8080
      - 19990:9990
    depends_on:
      - mysqldb
    environment:
      DB_VENDOR: mysql
      DB_ADDR: mysqldb
      DB_PORT: 3306
      DB_DATABASE: keycloak?createDatabaseIfNotExist=true
      DB_USER: root
      DB_PASSWORD: root
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
      KEYCLOAK_FRONTEND_URL: http://keycloak:8080/auth
      POSTGRES_PORT_5432_TCP_ADDR: 127.0.0.1

  zookeeper:
    image: "confluentinc/cp-zookeeper:5.2.1"
    networks:
      - transaction-network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2

  kafka:
    image: "confluentinc/cp-kafka:5.2.1"
    networks:
      - transaction-network
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  mysqldb:
    image: mysql:8.0.23
    ports:
      - "3050:3306"
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=transaction
    networks:
      - transaction-network

  transacoes:
    image: 'zupacademy/transacoes'
    networks:
      - transaction-network
    ports:
      - 7777:7777
    depends_on:
      - kafka
    environment:
      SERVER_PORT: 7777
      LOG_LEVEL: INFO
      KAFKA_HOST: "kafka:29092"

  transaction:
    build: .
    image: afonsompp/transaction
    container_name: transaction
    networks:
      - transaction-network
    ports:
      - "8081:8080"
    depends_on:
      - mysqldb
      - keycloak
    environment:
      KAFKA_TRANSACTION_TOPIC: transacoes
      KAFKA_HOST: kafka
      KAFKA_PORT: 29092
      KAFKA_GROUP_ID: transacoes
      TRANSACOES_HOST: transacoes
      TRANSACOES_PORT: 7777
      KEYCLOACK_URL: http://keycloak:8080/auth
      DB_USER: root
      DB_PASSWORD: root
      DB_URL: jdbc:mysql://mysqldb:3306/transaction?createDatabaseIfNotExist=true
      ACTIVE_PROFILE: docker

volumes:
  mysql-volume:

networks:
  transaction-network:
    driver: bridge
